<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GrpcProtoLibrary" Version="1.0.3" />
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
    <PackageReference Include="WebPortalSecurityManager" Version="1.0.6.6" />
    <PackageReference Include="DbOperations" Version="1.0.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
    <PackageReference Include="log4net" Version="3.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeManagement.Domain\TimeManagement.Domain.csproj" />
    <ProjectReference Include="..\TimeManagement.Infra\TimeManagement.Infra.csproj" />
  </ItemGroup>

</Project>
