<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
		<PackageReference Include="log4net" Version="3.2.0" />

		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />

		<PackageReference Include="AzureFileManager" Version="1.0.0.7" />
		<PackageReference Include="DbOperations" Version="1.0.0.4" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
		<PackageReference Include="WebPortalSecurityManager" Version="1.0.6.6" />

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TimeManagement.Infra\TimeManagement.Infra.csproj" />
		<ProjectReference Include="..\TimeManagement.Application\TimeManagement.Application.csproj" />
	</ItemGroup>

</Project>
