<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
    <PackageReference Include="log4net" Version="3.2.0" />
    <PackageReference Include="DbOperations" Version="1.0.0.4" />
    <PackageReference Include="WebPortalSecurityManager" Version="1.0.6.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeManagement.Domain\TimeManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Logging\log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
